# Generated by Django 6.0.4 on 2026-05-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_historicalattendance_historicallesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attempt_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='qr_code_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='verified_by_face',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalattendance',
            name='attempt_time',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalattendance',
            name='qr_code_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='historicalattendance',
            name='verified_by_face',
            field=models.BooleanField(default=False),
        ),
    ]
